### ISSUE TITLE
Making tutorial video would be awesome 

### ISSUE THREAD

**Issue by Zayon986** [meforce/holla#1]
![holla-cover-new.jpg](https://user-images.githubusercontent.com/95130510/150662949-57d56fe9-266e-4305-84d6-676a3d3ae958.jpg)
I saw this amazing desktop browser on CODECANYON.NET. I really love this product but I would like you to make a detailed tutorial on how to build it—(the building documentation is quite confusing) , am pretty sure that you are going to make great sales on codecanyon.net
I WAS LOOKING For a well understandable video tutorial about this but couldn't find it..
I will appreciate if you make a tutorial and add it to your codecayon account and Github as well thank you 😎 
Cheers 🥂

**Comment by meforce** [comment]
Thanks. More video documents will be added soon.

**Comment by Zayon986** [comment]
Alright really appreciate🙏

**Comment by meforce** [comment]
I forgot to reply. I am sad. Tutorial Video Live
https://www.youtube.com/watch?v=gHPFCXPd3LM&t=1s&ab_channel=MeForce
