### ISSUE TITLE
Website Errors

### ISSUE THREAD

**Issue by KorbsStudio** [meforce/holla#5]
![image](https://user-images.githubusercontent.com/51213244/168468106-ec5a0e14-a87e-4dbc-96da-c7b774a7747e.png)
**stay in touch**, the caps need to be placed and changed to **Stay in Touch**.

**Comment by meforce** [comment]
Provided editing. Thank you for your help.

docs/i18n/en.js
`345 "İletişimde kalın": "Stay in Touch",`
